# Generated by Django 2.0.3 on 2018-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=1, default=1.1, max_digits=2)),
                ('description', models.CharField(default='This is test app for awsome MYOB', max_length=50)),
                ('lastcommitsha', models.CharField(default='default', max_length=50)),
            ],
        ),
    ]
